### ISSUE TITLE
Please put a screenshot plus asciinema video on the front page.

### ISSUE THREAD

**Issue by unixbhaskar** [yegappan/fileselect#2]
So, as said in the subject line. So, people will get quickly familiar with the details. It's been practiced by all the plugin writer. I believe it helps.

**Comment by lacygoill** [comment]
Here is a short gif:

![gif](https://user-images.githubusercontent.com/8505073/103449956-c56a5500-4caf-11eb-8570-8ad1a102c9fa.gif)

**Comment by unixbhaskar** [comment]
Thanks.

**Comment by yegappan** [comment]
Thanks lacygoill for creating the ascii cinema. I have updated the Readme with this.
